#include "sqliteconnectioneditwidget.h"
#include "ui_sqliteconnectioneditwidget.h"

#include <QFileDialog>

SqliteConnectionEditWidget::SqliteConnectionEditWidget(MainWindow *parent) :
    QWidget(parent),
    ui(new Ui::SqliteConnectionEditWidget),
    parent(parent)
{
    ui->setupUi(this);
    connect(this->ui->openFileDialog, SIGNAL(clicked(bool)), this, SLOT(showFileDialog()));
}

void SqliteConnectionEditWidget::parseConnectionInfo(ConnectionInfo *connectionInfo) {
    if ("SQLITE" != connectionInfo->getConnectionType()) {
        return;
    }

    currentConnectionInfo = connectionInfo;

    if (true == connectionInfo->isConnectionNameAutogenerated()) {
        this->ui->connectionNameEdit->setPlaceholderText(connectionInfo->getConnectionName());
    } else {
        this->ui->connectionNameEdit->setText(connectionInfo->getConnectionName());
    }
    this->ui->databasePathEdit->setText(connectionInfo->getDatabasePath());
}

void SqliteConnectionEditWidget::showFileDialog() {
    QFileDialog dialog(parent);
    dialog.setFileMode(QFileDialog::AnyFile);
    if (dialog.exec()) {
        this->ui->databasePathEdit->setText(dialog.selectedFiles()[0]);
    }
}

void SqliteConnectionEditWidget::save() {

}

SqliteConnectionEditWidget::~SqliteConnectionEditWidget() {
    delete ui;
}
